# analyzer/html_generator.py - v3
"""
HTML 브리핑 생성기 — 5단락 시장 요약 + 강화된 카드 디자인
"""

import os
import re
from datetime import datetime
from zoneinfo import ZoneInfo

KST = ZoneInfo("Asia/Seoul")
ADMIN_PASSWORD = os.environ.get("ADMIN_PASSWORD", "stock2026!")


# ══════════════════════════════════════════════════════════════
#  메인 진입점
# ══════════════════════════════════════════════════════════════
def generate_html(
    analysis_result: dict,
    archive_dates: list = None,
    channels: dict = None,
    github_repo: str = "",
) -> str:
    now           = datetime.now(KST)
    briefing_date = analysis_result.get("briefing_date", now.strftime("%Y년 %m월 %d일"))
    market_summary = analysis_result.get("market_summary", {})
    s1_stocks     = analysis_result.get("section1_stocks", [])
    s2_stocks     = analysis_result.get("section2_stocks", [])
    s3_stocks     = analysis_result.get("section3_stocks", [])
    strategy      = analysis_result.get("investment_strategy", "")

    archive_bar   = _build_archive_links(archive_dates or [])
    s1_html       = _render_stock_cards(s1_stocks, section=1)
    s2_html       = _render_stock_cards(s2_stocks, section=2)
    s3_html       = _render_section3_cards(s3_stocks)
    market_html   = _render_market_summary(market_summary)
    strategy_html = _clean_markdown(strategy).replace("\n", "<br>")

    gen_time = now.strftime("%Y-%m-%d %H:%M KST")

    html = f"""<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>AI 주식 브리핑 — {briefing_date}</title>
{_get_css()}
</head>
<body>
<div class="container">

  <!-- 헤더 -->
  <header class="site-header">
    <div class="header-inner">
      <h1 class="logo">📈 AI 주식 브리핑</h1>
      <div class="header-meta">
        <span class="date-badge">{briefing_date}</span>
        <a href="admin/" class="admin-link">⚙ 관리</a>
      </div>
    </div>
  </header>

  <!-- 아카이브 바 -->
  {archive_bar}

  <!-- 시장 요약 -->
  <section class="market-summary-section">
    <h2 class="section-title">📊 오늘의 시장 요약</h2>
    {market_html}
  </section>

  <!-- 탭 네비게이션 -->
  <nav class="tab-nav">
    <button class="tab-btn active" data-tab="tab1">
      📹 유튜브 브리핑
      <span class="badge">{len(s1_stocks)}</span>
    </button>
    <button class="tab-btn" data-tab="tab2">
      📺 증권TV 분석
      <span class="badge">{len(s2_stocks)}</span>
    </button>
    <button class="tab-btn" data-tab="tab3">
      📋 애널리스트 리포트
      <span class="badge">{len(s3_stocks)}</span>
    </button>
    <button class="tab-btn" data-tab="tab4">
      💡 투자전략
    </button>
  </nav>

  <!-- 탭 컨텐츠 -->
  <div class="tab-content active" id="tab1">
    <div class="tab-header">
      <h2>유튜브·미디어 언급 종목</h2>
      <p class="tab-desc">방송·유튜브 채널에서 언급된 주요 종목 분석 (최근 24시간)</p>
    </div>
    {s1_html if s1_html else '<p class="no-data">수집된 데이터가 없습니다.</p>'}
  </div>

  <div class="tab-content" id="tab2">
    <div class="tab-header">
      <h2>증권TV 전문가 추천 종목</h2>
      <p class="tab-desc">증권TV 전문가 출연 방송 기반 추천 종목 (최근 48시간)</p>
    </div>
    {s2_html if s2_html else '<p class="no-data">수집된 데이터가 없습니다.</p>'}
  </div>

  <div class="tab-content" id="tab3">
    <div class="tab-header">
      <h2>증권사 애널리스트 리포트</h2>
      <p class="tab-desc">오늘 발간된 주요 증권사 분석 리포트</p>
    </div>
    {s3_html if s3_html else '<p class="no-data">수집된 데이터가 없습니다.</p>'}
  </div>

  <div class="tab-content" id="tab4">
    <div class="tab-header">
      <h2>💡 종합 투자전략</h2>
      <p class="tab-desc">섹션 1·2·3 통합 분석 기반 오늘의 투자 전략</p>
    </div>
    <div class="strategy-box">
      <p>{strategy_html}</p>
    </div>
  </div>

  <footer class="site-footer">
    <p>Generated by AI Stock Briefing v3 | {gen_time}</p>
    <p class="disclaimer">※ 본 브리핑은 AI가 자동 생성한 참고 자료이며, 투자 결정은 본인 판단 하에 이루어져야 합니다.</p>
  </footer>

</div>
{_get_js()}
</body>
</html>"""

    _inject_admin_password()
    return html


# ══════════════════════════════════════════════════════════════
#  시장 요약 렌더링 (5단락)
# ══════════════════════════════════════════════════════════════
def _render_market_summary(summary: dict) -> str:
    """5단락 구조 시장 요약 렌더링"""

    if isinstance(summary, str):
        # 구버전 호환: 단순 문자열
        cleaned = _clean_markdown(summary).replace("\n", "<br>")
        return f'<div class="market-summary-text">{cleaned}</div>'

    if not isinstance(summary, dict):
        return '<p class="no-data">시장 요약 데이터 없음</p>'

    # 수치 데이터
    night   = summary.get("night_futures_data", {})
    us      = summary.get("us_market_data", {})
    korea   = summary.get("korea_market_data", {})

    sp    = us.get("sp500",  {})
    nq    = us.get("nasdaq", {})
    dw    = us.get("dow",    {})
    fx    = us.get("usd_krw", {})
    kp    = korea.get("kospi",  {})
    kd    = korea.get("kosdaq", {})

    direction = night.get("direction", "neutral")
    dir_icon  = "🟢" if direction == "call" else ("🔴" if direction == "put" else "🟡")
    dir_label = "콜(상승)" if direction == "call" else ("풋(하락)" if direction == "put" else "중립")
    dir_class = "call" if direction == "call" else ("put" if direction == "put" else "neutral")

    def pct_html(pct, price=None):
        if pct is None:
            return '<span class="no-val">N/A</span>'
        cls = "up" if float(pct) > 0 else ("down" if float(pct) < 0 else "flat")
        arrow = "▲" if float(pct) > 0 else ("▼" if float(pct) < 0 else "─")
        price_str = f"{float(price):,.0f} " if price else ""
        return f'<span class="chg {cls}">{price_str}{arrow}{abs(float(pct)):.2f}%</span>'

    # 수치 배지 행
    indicators_html = f"""
    <div class="market-indicators">
      <div class="indicator-card {dir_class}">
        <span class="ind-label">야간선물</span>
        <span class="ind-value">{dir_icon} {dir_label}</span>
        <span class="ind-sub">{night.get('signal','')}</span>
      </div>
      <div class="indicator-card">
        <span class="ind-label">S&P500</span>
        <span class="ind-value">{pct_html(sp.get('change_pct'), sp.get('price'))}</span>
      </div>
      <div class="indicator-card">
        <span class="ind-label">나스닥</span>
        <span class="ind-value">{pct_html(nq.get('change_pct'), nq.get('price'))}</span>
      </div>
      <div class="indicator-card">
        <span class="ind-label">다우</span>
        <span class="ind-value">{pct_html(dw.get('change_pct'), dw.get('price'))}</span>
      </div>
      <div class="indicator-card">
        <span class="ind-label">달러/원</span>
        <span class="ind-value">{pct_html(fx.get('change_pct'), fx.get('price'))}</span>
      </div>
      <div class="indicator-card">
        <span class="ind-label">코스피</span>
        <span class="ind-value">{pct_html(kp.get('change_pct'), kp.get('price'))}</span>
      </div>
      <div class="indicator-card">
        <span class="ind-label">코스닥</span>
        <span class="ind-value">{pct_html(kd.get('change_pct'), kd.get('price'))}</span>
      </div>
    </div>"""

    # 5단락 텍스트
    paragraphs = [
        ("🌙 야간선물 동향 및 콜/풋 예측", "night_futures_para"),
        ("🇺🇸 미국 증시 마감 동향",         "us_market_para"),
        ("🇰🇷 전일 한국 증시 흐름",          "korea_prev_para"),
        ("🔮 오늘 예상 흐름",               "today_outlook_para"),
        ("🎯 주요 관심 섹터",               "sector_para"),
    ]

    paras_html = ""
    for title, key in paragraphs:
        content = summary.get(key, "")
        if not content:
            continue
        cleaned = _clean_markdown(content).replace("\n", "<br>")
        paras_html += f"""
    <div class="summary-para">
      <h3 class="para-title">{title}</h3>
      <p class="para-body">{cleaned}</p>
    </div>"""

    return f"""
  <div class="market-summary-wrap">
    {indicators_html}
    <div class="summary-paras">
      {paras_html}
    </div>
  </div>"""


# ══════════════════════════════════════════════════════════════
#  종목 카드 렌더링
# ══════════════════════════════════════════════════════════════
def _render_stock_cards(stocks: list, section: int = 1) -> str:
    if not stocks:
        return ""
    cards = "".join(_stock_card(s, section) for s in stocks)
    return f'<div class="stock-grid">{cards}</div>'


def _stock_card(s: dict, section: int) -> str:
    name     = s.get("stock_name", "")
    source   = s.get("source_name", "")
    price_d  = s.get("price_display", "")
    trend    = s.get("price_trend", "")
    reasons  = s.get("reasons", [])
    sentiment = s.get("sentiment", "")
    rec      = s.get("recommendation", "")

    sentiment_cls = "pos" if sentiment == "긍정" else ("neg" if sentiment == "부정" else "neu")
    rec_cls   = {"매수": "buy", "매도": "sell", "보유": "hold", "관심": "watch"}.get(rec, "neu")

    badge_html = ""
    if sentiment:
        badge_html = f'<span class="badge-sentiment {sentiment_cls}">{sentiment}</span>'
    if rec:
        badge_html += f'<span class="badge-rec {rec_cls}">{rec}</span>'

    price_html = ""
    if price_d:
        price_html = f'<div class="price-display">{price_d}</div>'
    if trend:
        price_html += f'<div class="price-trend">{trend}</div>'

    reasons_html = _render_reasons(reasons)

    return f"""
  <div class="stock-card">
    <div class="card-header">
      <span class="stock-name">{name}</span>
      <div class="card-badges">{badge_html}</div>
    </div>
    <div class="card-source">{source}</div>
    {price_html}
    {reasons_html}
  </div>"""


def _render_section3_cards(stocks: list) -> str:
    if not stocks:
        return ""
    cards = "".join(_s3_card(s) for s in stocks)
    return f'<div class="stock-grid">{cards}</div>'


def _s3_card(s: dict) -> str:
    name      = s.get("stock_name", "")
    broker    = s.get("source_name", "")
    title     = s.get("report_title", "")
    tp        = s.get("target_price", "")
    opinion   = s.get("opinion", "")
    cat       = s.get("analyst_category", "general")
    reasons   = s.get("reasons", [])
    price_d   = s.get("price_display", "")

    cat_labels = {
        "simultaneous": ("🔥 동시언급", "cat-sim"),
        "new_coverage": ("🆕 신규커버", "cat-new"),
        "first_in_6months": ("⭐ 6개월첫언급", "cat-first"),
    }
    cat_label, cat_cls = cat_labels.get(cat, ("", ""))
    cat_html = f'<span class="cat-badge {cat_cls}">{cat_label}</span>' if cat_label else ""

    tp_html = _fmt_target_price(tp)

    op_cls  = {"매수": "op-buy", "중립": "op-hold", "매도": "op-sell"}.get(opinion, "op-neu")
    op_html = f'<span class="opinion-badge {op_cls}">{opinion}</span>' if opinion else ""

    price_html = f'<div class="price-display">{price_d}</div>' if price_d else ""
    title_html = f'<div class="report-title">{_clean_markdown(title)}</div>' if title else ""

    reasons_html = _render_reasons(reasons)

    return f"""
  <div class="stock-card s3-card">
    <div class="card-header">
      <span class="stock-name">{name}</span>
      <div class="card-badges">{cat_html}{op_html}</div>
    </div>
    <div class="card-source">{broker} {tp_html}</div>
    {title_html}
    {price_html}
    {reasons_html}
  </div>"""


def _render_reasons(reasons: list) -> str:
    if not reasons:
        return ""
    items = "".join(
        f'<li>{_clean_markdown(str(r))}</li>' for r in reasons if r
    )
    return f'<ul class="reason-list">{items}</ul>'


def _fmt_target_price(tp) -> str:
    if not tp:
        return ""
    tp_clean = str(tp).replace(",", "").replace("원", "").strip()
    try:
        return f'<span class="target-price">목표가 {int(tp_clean):,}원</span>'
    except ValueError:
        return f'<span class="target-price">목표가 {tp}</span>' if tp else ""


def _clean_markdown(text: str) -> str:
    """마크다운 기호를 HTML 친화적으로 변환"""
    if not text:
        return ""
    text = re.sub(r'^#{1,4}\s+', '', text, flags=re.MULTILINE)
    text = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', text)
    text = re.sub(r'\*(.+?)\*', r'<em>\1</em>', text)
    text = re.sub(r'`(.+?)`', r'<code>\1</code>', text)
    text = re.sub(r'^[-*]\s+', '• ', text, flags=re.MULTILINE)
    return text.strip()


# ══════════════════════════════════════════════════════════════
#  어드민 패스워드 주입
# ══════════════════════════════════════════════════════════════
def _inject_admin_password():
    path = "docs/admin/index.html"
    if not os.path.exists(path):
        return
    try:
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
        if "%%ADMIN_PASSWORD%%" in content:
            content = content.replace("%%ADMIN_PASSWORD%%", ADMIN_PASSWORD)
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
    except Exception as e:
        print(f"  [admin] 패스워드 주입 실패: {e}")


# ══════════════════════════════════════════════════════════════
#  아카이브 링크
# ══════════════════════════════════════════════════════════════
def _build_archive_links(dates: list) -> str:
    if not dates:
        return ""
    links = "".join(
        f'<a href="archive/{d}.html" class="archive-link">{d}</a>'
        for d in dates[:10]
    )
    return f'<div class="archive-bar"><span class="archive-label">📁 과거 브리핑:</span>{links}</div>'


# ══════════════════════════════════════════════════════════════
#  CSS
# ══════════════════════════════════════════════════════════════
def _get_css() -> str:
    return """
<style>
:root {
  --bg:        #0d1117;
  --surface:   #161b22;
  --surface2:  #21262d;
  --border:    #30363d;
  --text:      #e6edf3;
  --text-sub:  #8b949e;
  --accent:    #58a6ff;
  --green:     #3fb950;
  --red:       #f85149;
  --yellow:    #d29922;
  --purple:    #bc8cff;
  --radius:    10px;
}
* { box-sizing: border-box; margin: 0; padding: 0; }
body {
  background: var(--bg);
  color: var(--text);
  font-family: 'Malgun Gothic', 'Apple SD Gothic Neo', sans-serif;
  font-size: 15px;
  line-height: 1.6;
}
.container { max-width: 1100px; margin: 0 auto; padding: 0 16px 60px; }

/* 헤더 */
.site-header {
  background: linear-gradient(135deg, #0d1117 0%, #161b22 100%);
  border-bottom: 1px solid var(--border);
  padding: 20px 0;
  margin-bottom: 16px;
}
.header-inner {
  display: flex; align-items: center; justify-content: space-between;
}
.logo { font-size: 1.5rem; font-weight: 700; color: var(--accent); }
.header-meta { display: flex; align-items: center; gap: 12px; }
.date-badge {
  background: var(--surface2);
  border: 1px solid var(--border);
  border-radius: 20px;
  padding: 4px 14px;
  font-size: 0.85rem;
  color: var(--text-sub);
}
.admin-link {
  color: var(--text-sub);
  text-decoration: none;
  font-size: 0.82rem;
  padding: 4px 10px;
  border: 1px solid var(--border);
  border-radius: 6px;
  transition: color 0.2s;
}
.admin-link:hover { color: var(--accent); border-color: var(--accent); }

/* 아카이브 바 */
.archive-bar {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  padding: 8px 16px;
  margin-bottom: 20px;
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  align-items: center;
  font-size: 0.82rem;
}
.archive-label { color: var(--text-sub); margin-right: 4px; }
.archive-link {
  color: var(--accent);
  text-decoration: none;
  padding: 2px 8px;
  border-radius: 4px;
  background: var(--surface2);
  transition: background 0.2s;
}
.archive-link:hover { background: var(--border); }

/* 시장 요약 섹션 */
.market-summary-section {
  margin-bottom: 28px;
}
.section-title {
  font-size: 1.15rem;
  font-weight: 700;
  color: var(--text);
  margin-bottom: 14px;
  padding-left: 4px;
  border-left: 3px solid var(--accent);
}

/* 수치 인디케이터 */
.market-indicators {
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
  margin-bottom: 20px;
}
.indicator-card {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  padding: 12px 16px;
  min-width: 120px;
  display: flex;
  flex-direction: column;
  gap: 4px;
}
.indicator-card.call { border-color: var(--green); background: rgba(63,185,80,0.08); }
.indicator-card.put  { border-color: var(--red);   background: rgba(248,81,73,0.08); }
.indicator-card.neutral { border-color: var(--yellow); }
.ind-label { font-size: 0.75rem; color: var(--text-sub); }
.ind-value { font-size: 0.95rem; font-weight: 700; }
.ind-sub   { font-size: 0.72rem; color: var(--text-sub); }

/* 등락 색상 */
.chg.up   { color: var(--green); }
.chg.down { color: var(--red); }
.chg.flat { color: var(--text-sub); }
.no-val   { color: var(--text-sub); }

/* 5단락 */
.summary-paras {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
  gap: 14px;
}
.summary-para {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  padding: 16px 18px;
}
.para-title {
  font-size: 0.95rem;
  font-weight: 700;
  color: var(--accent);
  margin-bottom: 8px;
}
.para-body {
  font-size: 0.88rem;
  color: var(--text);
  line-height: 1.65;
}

/* 탭 네비 */
.tab-nav {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
  margin-bottom: 20px;
  border-bottom: 1px solid var(--border);
  padding-bottom: 10px;
}
.tab-btn {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  color: var(--text-sub);
  cursor: pointer;
  font-size: 0.88rem;
  padding: 8px 16px;
  transition: all 0.2s;
  display: flex;
  align-items: center;
  gap: 6px;
}
.tab-btn:hover  { border-color: var(--accent); color: var(--text); }
.tab-btn.active { background: var(--accent); border-color: var(--accent); color: #fff; }
.badge {
  background: rgba(255,255,255,0.2);
  border-radius: 10px;
  font-size: 0.75rem;
  padding: 1px 7px;
}

/* 탭 컨텐츠 */
.tab-content { display: none; }
.tab-content.active { display: block; }
.tab-header { margin-bottom: 18px; }
.tab-header h2 { font-size: 1.05rem; font-weight: 700; margin-bottom: 4px; }
.tab-desc { font-size: 0.82rem; color: var(--text-sub); }

/* 종목 그리드 */
.stock-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
  gap: 14px;
}
.stock-card {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  padding: 16px;
  transition: border-color 0.2s, transform 0.15s;
}
.stock-card:hover {
  border-color: var(--accent);
  transform: translateY(-2px);
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  margin-bottom: 6px;
}
.stock-name {
  font-size: 1rem;
  font-weight: 700;
  color: var(--text);
}
.card-badges { display: flex; flex-wrap: wrap; gap: 4px; }
.card-source {
  font-size: 0.78rem;
  color: var(--text-sub);
  margin-bottom: 8px;
  display: flex;
  align-items: center;
  gap: 6px;
}

/* 배지 */
.badge-sentiment, .badge-rec, .cat-badge, .opinion-badge {
  border-radius: 4px;
  font-size: 0.72rem;
  font-weight: 600;
  padding: 2px 7px;
}
.badge-sentiment.pos { background: rgba(63,185,80,0.15); color: var(--green); }
.badge-sentiment.neg { background: rgba(248,81,73,0.15); color: var(--red); }
.badge-sentiment.neu { background: var(--surface2); color: var(--text-sub); }
.badge-rec.buy  { background: rgba(63,185,80,0.15); color: var(--green); }
.badge-rec.sell { background: rgba(248,81,73,0.15); color: var(--red); }
.badge-rec.hold { background: rgba(210,153,34,0.15); color: var(--yellow); }
.badge-rec.watch { background: rgba(88,166,255,0.15); color: var(--accent); }
.cat-badge.cat-sim   { background: rgba(248,81,73,0.15); color: var(--red); }
.cat-badge.cat-new   { background: rgba(63,185,80,0.15); color: var(--green); }
.cat-badge.cat-first { background: rgba(188,140,255,0.15); color: var(--purple); }
.op-buy  { background: rgba(63,185,80,0.15); color: var(--green); }
.op-sell { background: rgba(248,81,73,0.15); color: var(--red); }
.op-hold { background: rgba(210,153,34,0.15); color: var(--yellow); }
.op-neu  { background: var(--surface2); color: var(--text-sub); }

/* 가격 */
.price-display {
  font-size: 0.88rem;
  color: var(--accent);
  font-weight: 600;
  margin-bottom: 4px;
}
.price-trend {
  font-size: 0.78rem;
  color: var(--text-sub);
  margin-bottom: 8px;
}
.target-price {
  font-size: 0.78rem;
  color: var(--yellow);
  font-weight: 600;
}
.report-title {
  font-size: 0.82rem;
  color: var(--text-sub);
  margin-bottom: 8px;
  font-style: italic;
}

/* 이유 리스트 */
.reason-list {
  list-style: none;
  margin-top: 8px;
}
.reason-list li {
  font-size: 0.82rem;
  color: var(--text-sub);
  padding: 3px 0 3px 14px;
  position: relative;
  border-bottom: 1px solid var(--surface2);
}
.reason-list li:last-child { border-bottom: none; }
.reason-list li::before {
  content: "›";
  position: absolute;
  left: 0;
  color: var(--accent);
  font-weight: 700;
}

/* 투자전략 */
.strategy-box {
  background: var(--surface);
  border: 1px solid var(--accent);
  border-radius: var(--radius);
  padding: 24px;
  font-size: 0.93rem;
  line-height: 1.8;
  color: var(--text);
}

/* 기타 */
.no-data { color: var(--text-sub); padding: 40px; text-align: center; font-size: 0.9rem; }
.market-summary-text {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  padding: 18px;
  font-size: 0.9rem;
  line-height: 1.7;
}

/* 푸터 */
.site-footer {
  text-align: center;
  margin-top: 60px;
  padding-top: 20px;
  border-top: 1px solid var(--border);
  color: var(--text-sub);
  font-size: 0.8rem;
}
.disclaimer { margin-top: 6px; font-size: 0.75rem; }

/* 반응형 */
@media (max-width: 600px) {
  .stock-grid { grid-template-columns: 1fr; }
  .summary-paras { grid-template-columns: 1fr; }
  .market-indicators { flex-direction: column; }
  .indicator-card { min-width: unset; }
}
</style>"""


# ══════════════════════════════════════════════════════════════
#  JS
# ══════════════════════════════════════════════════════════════
def _get_js() -> str:
    return """
<script>
document.querySelectorAll('.tab-btn').forEach(btn => {
  btn.addEventListener('click', () => {
    document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
    document.querySelectorAll('.tab-content').forEach(c => c.classList.remove('active'));
    btn.classList.add('active');
    document.getElementById(btn.dataset.tab).classList.add('active');
  });
});
</script>"""
